# Generated by Django 3.2.17 on 2024-05-15 00:00
from django.db import migrations, models


def populate_theme(apps, schema_editor):
    UserDarkModeProperties = apps.get_model("users", "UserDarkModeProperties")
    for props in UserDarkModeProperties.objects.all():
        props.theme = "dark-classic" if props.dark_mode_enabled else "light"
        props.save(update_fields=["theme"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_user_seen_april_fools"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdarkmodeproperties",
            name="theme",
            field=models.CharField(choices=[("light", "Light"), ("dark-classic", "Dark (classic)"), ("dark-twilight", "Twilight (dark)")], default="light", max_length=32),
        ),
        migrations.RunPython(populate_theme, migrations.RunPython.noop),
    ]
